 export const baceOptions = [
        "Ayodhya Dham",
        "Badrinath Dham",
        "Braj Dham",
        "Ekachakra Dham",
        "Gambhira",
        "Gaur Dham",
        "Goverdhan Dham",
        "Govind Dham",
        "Gurugram BACE",
        "Indraprastha Dham",
        "Jagannath Puri Dham",
        "Mamgachchi",
        "Mathura Dham",
        "Mayapur Dham",
        "Nadiya Dham",
        "Shantipur Dham",
        "Srivas Angan",
        "Temple",
        "Tughlakabad Center",
        "Others",
    ];
   export const instituteOptions = [
        "AIIMS",
        "Akhilesh Das Gupta College",
        "Amity University Noida",
        "DGI, Greate Noida",
        "DSEU Ashok Vihar Campus",
        "DU",
        "Nalanda",
        "GNIOT",
        "GL Bajaj",
        "IEC",
        "IGNOU",
        "IILM University",
        "Innovation institute",
        "ISAB",
        "Jaipuria School of Business",
        "JNU",
        "Motilal Nehru College",
        "NIU",
        "Sharda University",
        "Swami Shraddhanand College",
        "United Engg College",
        "VMMC - Safdarjung",
    ];