 export const baceOptions = [
        "Ayodhya Dham",
        "Badrinath Dham",
        "Braj Dham",
        "Ekachakra Dham",
        "Gambhira",
        "Gaur Dham",
        "Goverdhan Dham",
        "Govind Dham",
        "Gurugram BACE",
        "Indraprastha Dham",
        "Jagannath Puri Dham",
        "Mamgachchi",
        "Mathura Dham",
        "Mayapur Dham",
        "Nadiya Dham",
        "Shantipur Dham",
        "Srivas Angan",
        "Temple",
        "Tughlakabad Center",
        "Others",
    ];
   export const collegeOptions = [
        "AIIMS",
        "Akhilesh Das Gupta College",
        "Amity University Noida",
        "DGI, Greate Noida",
        "DSEU Ashok Vihar Campus",
        "DU",
        "Nalanda",
        "GNIOT",
        "GL Bajaj",
        "IEC",
        "IGNOU",
        "IILM University",
        "Innovation institute",
        "ISAB",
        "Jaipuria School of Business",
        "JNU",
        "Motilal Nehru College",
        "NIU",
        "Sharda University",
        "Swami Shraddhanand College",
        "United Engg College",
        "VMMC - Safdarjung",
    ];

    export const schoolOptions = [
  "Delhi Public School (DPS), Greater Noida",
  "Delhi Public School (DPS), Noida",
  "Step by Step School, Noida",
  "Lotus Valley International School, Noida",
  "Ryan International School, Greater Noida",
  "Apeejay School, Noida",
  "Somerville School, Greater Noida",
  "Genesis Global School, Noida",
  "Shiv Nadar School, Noida",
  "Kothari International School, Noida",
  "Bal Bharati Public School, Noida",
  "The Millennium School, Greater Noida",
  "G.D. Goenka Public School, Greater Noida",
  "Cambridge School, Noida",
  "Jaypee Public School, Greater Noida",
  "Bloom International School, Greater Noida",
  "Billabong High International School, Noida",
  "Sarvottam International School, Greater Noida",
  "Vishwa Bharati Public School, Noida",
  "Mayoor School, Noida",
  "Assisi Convent School, Noida",
  "Manthan School, Greater Noida",
  "St. Joseph’s School, Greater Noida",
  "Fr. Agnel School, Noida",
  "JBM Global School, Noida",
];
